### ISSUE TITLE
Code for training wav2vec

### ISSUE THREAD

**Issue by JNaranjo-Alcazar** [XinhaoMei/DCASE2021_task6_v2#2]
Is available the code for training the wav2vec model as described in the technical report or is just released in pre-trained models folder?

Thanks for sharing!

**Comment by XinhaoMei** [comment]
> Is available the code for training the wav2vec model as described in the technical report or is just released in pre-trained models folder?
> 
> Thanks for sharing!

Hi, do you mean the word2vec model? 
I have uploaded the code for training word2vec model in word2vec_train.py
BTW, I run this code with gensim 3.8.3 (which is 4.0.1 in the environmental dependencies) .

**Comment by JNaranjo-Alcazar** [comment]
Yes! That is why I was looking for!

Thanks for the quick reply!
