### ISSUE TITLE
About the sample rate and hop length

### ISSUE THREAD

**Issue by XinMing0411** [XinhaoMei/DCASE2021_task6_v2#3]
I saw that your parameter settings are very different from those of PANN.
The hop length = 512 , sample rate = 44100 in your project ; but in PANN ,these parameters are different from you. 
Do these parameters affect the experimental results？ and do I need to set the acoustic feature extraction parameters the same as Pann？
Thank you very much~

**Comment by XinhaoMei** [comment]
Hi, 
The sampling rate of Clotho is 44.1kHz, and I didn't change the sampling rate when I created the dataset. If you are using my code to create the dataset and want to change the sampling rate of the waveform, you can change the sampling rate in this [script](https://github.com/XinhaoMei/DCASE2021_task6_v2/blob/main/tools/dataset.py).
In Qiuqiang's PANNs, the default sampling rate is 32kHz and he used torchlibrosa to extract the log mel-spectrogram, thus when I load the pre-trained PANNs I didn't load the first two layers that used for extracting log mel-spectrogram but initialize them with my sampling rate and hop size, you can find them [here](https://github.com/XinhaoMei/DCASE2021_task6_v2/blob/main/models/TransModel.py). 
In fact, I have tried both two sampling rates, there were only minor differences in terms of the performance in my experiments.
