### ISSUE TITLE
Difference with ACT

### ISSUE THREAD

**Issue by Ynjxsjmh** [XinhaoMei/DCASE2021_task6_v2#5]
Hi,

In my opinion, model structure in this repo is the same with your [ACT](https://github.com/XinhaoMei/ACT) model, they both use a full Transformer network based on an encoder-decoder architecture.

[This paper](https://arxiv.org/pdf/2108.02752.pdf) further uses transfer learning and reinforcement learning to fine tune the parameters, but why the result in this paper is worse than the [ACT](https://arxiv.org/pdf/2107.09817.pdf)?

![image](https://user-images.githubusercontent.com/40143136/158006725-8619ffb6-abe5-4046-b8fd-4f382fd2b550.png)

![image](https://user-images.githubusercontent.com/40143136/158006730-05eb131b-3163-4e59-a8c1-5f1bae892717.png)

Take following two models as an example:

| Model       | BLEU1       | BLEU2 | BLEU3 | BLEU4 | ROUGEL | METERO | CIDEr | SPICE | SPIDEr |
| ----------- | ----------- | ----- | ----- | ----- | -----  | -----  | ----- | ----- | -----  |
| ACT_m_DeiT_AudioSet | 0.653 | 0.495 | 0.363 | 0.259 | 0.471 | 0.222 | 0.663 | 0.163 | 0.413 |
| B+PANNs+AC+RL       | 0.634 | 0.423 | 0.288 | 0.185 | 0.410 | 0.187 | 0.476 | 0.134 | 0.305 |

**Comment by XinhaoMei** [comment]
Hi, thanks for your interest.
First, the DECASE model is based on a CNN-Transformer architecture, not a full transformer model like ACT.
Second, they are evaluated on different datasets. ACT is evaluated on AudioCaps and DECASE model is evaluated on Clotho.

**Comment by Ynjxsjmh** [comment]
Thanks for your reply, I can well understand now. Some DECASE models are pretrained on AudioCaps and all are evaluated on Clotho.
