### ISSUE TITLE
about coco_caption

### ISSUE THREAD

**Issue by TianyangHuang** [XinhaoMei/DCASE2021_task6_v2#6]
when i run the train.py , i encountered some difficulties,
I've tried re-downloading coco_caption to no avail, and I thought at first that there wasn't enough memory, and after re-running it I still got the same error.
Can you give me some advice? 
Thank you
`Traceback (most recent call last):
  File "train.py", line 323, in <module>
    eval_beam(evaluation_data, beam_size=2)
  File "train.py", line 142, in eval_beam
    beam_metrics = evaluate_metrics(captions_pred, captions_gt)
  File "/data/shaoxi/hty_all/task6_v2/eval_metrics.py", line 293, in evaluate_metrics
    metrics, per_file_metrics = evaluate_metrics_from_lists(predictions, ground_truths)
  File "/data/shaoxi/hty_all/task6_v2/eval_metrics.py", line 165, in evaluate_metrics_from_lists
    metrics, per_file_metrics = evaluate_metrics_from_files(pred_file, ref_file)
  File "/data/shaoxi/hty_all/task6_v2/eval_metrics.py", line 112, in evaluate_metrics_from_files
    cocoEval.evaluate(verbose=False)
  File "/data/shaoxi/hty_all/task6_v2/coco_caption/pycocoevalcap/eval.py", line 62, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/data/shaoxi/hty_all/task6_v2/coco_caption/pycocoevalcap/spice/spice.py", line 75, in compute_score
    cwd=os.path.dirname(os.path.abspath(__file__)))
  File "/home/user1/.conda/envs/hty/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/data/shaoxi/hty_all/task6_v2/coco_caption/pycocoevalcap/spice/tmp/tmpzce3f7z7', '-cache', '/data/shaoxi/hty_all/task6_v2/coco_caption/pycocoevalcap/spice/cache', '-out', '/data/shaoxi/hty_all/task6_v2/coco_caption/pycocoevalcap/spice/tmp/tmpvpuknq04', '-subset', '-silent']' returned non-zero exit status 1.`

**Comment by XinhaoMei** [comment]
Hi, I also encountered this problem sometime. 
[This](https://github.com/audio-captioning/dcase-2020-baseline/issues/6) might be helpful.

**Comment by TianyangHuang** [comment]
> 你好，我以前也遇到过这个问题。 [这](https://github.com/audio-captioning/dcase-2020-baseline/issues/6)可能会有所帮助。

thank you for you reply! I will try it today.

**Comment by XinhaoMei** [comment]
> > 你好，我以前也遇到过这个问题。 [这](https://github.com/audio-captioning/dcase-2020-baseline/issues/6)可能会有所帮助。
> 
> thank you for you reply! I will try it today.

Hi, another solution for me is increasing the memory, for example, I tried 'Xmx40G' and didn't get this error.

**Comment by TianyangHuang** [comment]
> 

Thank you very much for your answer, I was worried about this, because the previous method didn't work for me. I will add more memory to try. Thanks again for your answer!

**Comment by TianyangHuang** [comment]
> > > 你好，我以前也遇到过这个问题。 [这](https://github.com/audio-captioning/dcase-2020-baseline/issues/6)可能会有所帮助。
> > 
> > 
> > thank you for you reply! I will try it today.
> 
> Hi, another solution for me is increasing the memory, for example, I tried 'Xmx40G' and didn't get this error.

The 'Xmx40G' is worked for me, Thank you very much for your answer.I don't know if it's convenient to add your WeChat, I am also doing T6 this year, I hope to have the opportunity to communicate with you to learn. :D

**Comment by XinhaoMei** [comment]
Of courese, mine is mxh511185064.
